### PR TITLE
Implement buffer direct allocation in FIXValue

### PR DESCRIPTION
**Pull request by arturo-salinas**
This pull request is meant for discussion and early feedback. 

I thought using a ByteBuffer (with direct allocation) as storage instead of an array could improve performance but my experiments show that the performance has actually decreased (see attached result files).
[output_test_original.txt](https://github.com/paritytrading/philadelphia/files/3308209/output_test_original.txt)
[output_test_bytebuffer.txt](https://github.com/paritytrading/philadelphia/files/3308210/output_test_bytebuffer.txt). 

However, it looks that the benchmark: asString has improved. 

In another experiment I noticed that direct allocation has actually decreased the performance further. 

Next steps could be to not use direct allocation and to do the ByteBuffer allocation in FIXMessage. But I will wait for feedback.

### CODE REVIEW

**Comment by arturo-salinas** [comment]
This pull request is meant for discussion and early feedback. 

I thought using a BufferBytes as storage instead of an array could improve performance but my experiments show that the performance has actually decreased (see attached result files).
[output_test_original.txt](https://github.com/paritytrading/philadelphia/files/3308209/output_test_original.txt)
[output_test_bytebuffer.txt](https://github.com/paritytrading/philadelphia/files/3308210/output_test_bytebuffer.txt). 

However, it looks that the benchmark: asString has improved.

**Comment by jvirtanen** [comment]
Interesting experiments, @arturo-salinas! I will have a look. 🔍

**Comment by jvirtanen** [comment]
I took a bit of time to think about this. 💡 

In the big picture, what we would like to optimize are the following paths:
- values are formatted into an outgoing message and the message is written to the network
- an incoming message is read from the network and values are parsed from it

Currently this is implemented as follows:
- when writing a value, e.g. with `FIXValue#setInt`, the FIX value representation is formatted into a byte array maintained by the `FIXValue` object
- when reading a value, e.g. with `FIXValue#asInt`, the FIX value representation is parsed from the byte array maintained by the `FIXValue` object
- when sending a message, the `FIXValue` objects maintained by the `FIXMessage` instance are sequentially written out into the (direct) transmission `ByteBuffer`
- when receiving a message, the `FIXValue` objects maintained by the `FIXMessage` instance are sequentially read in from the (direct) receive `ByteBuffer`

Now, having a byte array as a backing store for a `FIXValue` object is likely faster for formatting and parsing the FIX value representation. A non-direct `ByteBuffer` is essentially just a wrapper around a byte array, and a direct `ByteBuffer` is backed by memory outside of the Java heap. Typically bulk operations are faster with a direct `ByteBuffer` than a non-direct `ByteBuffer` whereas writing and reading single bytes tends to be slower. Finally, to actually write bytes to the network using NIO, they have to reside in a direct `ByteBuffer`. (If you don't put them into one by yourself, NIO will do this for you.)

(Note that many `FIXValue` methods are also currently under 35 bytes and inline well even on the C1 compiler. If the byte array is replaced by `ByteBuffer`, this is likely no longer the case.)

Also your performance test results seem to corroborate the above statements.

In the vein of what you mention in the pull request description, one very interesting thing to try out would be to use one contiguous byte array for all `FIXValue` objects within a `FIXMessage` instance. This byte array would be owned by the `FIXMessage` object, and each `FIXValue` instance would get a "slice" of it (an offset and a length).

What do you think, @arturo-salinas?

**Comment by arturo-salinas** [comment]
I am continuing with the experiments. In the last commit I created a common ByteBuffer buffer which is allocated in FIXMessage. However, as the performance results show this is not a good idea. 

The problem with the parsing of incoming messages is that we are sequentially reading (getting) each byte of the direct ByteBuffer buffer where the message is placed. We cannot use buck operations because we do not know the length of each FIXValue (we do not know where the SOH mark is located). What I can try next is to use a buck copy from the direct ByteBuffer where the message is placed to a common ByteBuffer located in the heap which will be used for all the FIXValue objects. We can do that because we know the total length of the body. Then I think we can remove the array of int's which represents the tags and store the tag value inside FIXValue. At the moment of reading (getting) the FIX value, FIXValue will get a ByteBuffer slice of the common ByteBuffer which represents the FIX tag and FIX value. I hope this operation will be faster because it will be done just in the heap.

I also noticed that when the checksum is enabled; the sequential read of the direct ByteBuffer is done twice. What about to do the checksum at the same time when we are reading the FIX tag and FIX value, @jvirtanen? I guess the case when the checksum is not enabled will be a little bit slower because I would need to add a "if" each time a byte is read.

For the outgoing message I think it is durable to idea of the issue #95; we can replace the addField of FIXMessage for new methods such as addInt(tag, value), etc. Each of these methods will write to the common ByteBuffer (heap) directly and this will mean the "set" methods of FIXValue will be moved to FIXMessage. Then we can do a buck copy of the common ByteBuffer of FIXMessage to the direct ByteBuffer where the message is supposed to be sent. 

Any comments, @jvirtanen ?

**Comment by arturo-salinas** [comment]
@jvirtanen I implemented a buffer for outgoing messages in FIXMessage. It looks that performance has been increased for FIXMessageBenchmark.formatAndPut.

**Comment by arturo-salinas** [comment]
Here I attached the result of the performance tests:

[output_test_original.txt](https://github.com/paritytrading/philadelphia/files/3413513/output_test_original.txt)
[output_test_outgoing_new.txt](https://github.com/paritytrading/philadelphia/files/3413514/output_test_outgoing_new.txt)

**Comment by ddimtirov** [comment]
Keep in mind that even a heap `ByteBuffer` has a lot of range checks which are not always optimized away (or take a long time and many optimization cycles to optimize). 

I'd recommend to keep a private reference to the HBB's backing array and use directly in performance sensitive spots such as parsing. Even better, introduce the notion of message pool - a class that allocates one large array of bytes and can create messages with backing byte buffers wrapping slices of it. This guarantees cache locality, and you can do fancy stuff to ensure alignment.

It is kind of run of the mill design, so you may want to look around to see if you can copy anything (i.e. out of the Aeron ecosystem)

**Comment by jvirtanen** [comment]
Closing this for now.

**Pull request closed without merging**
